config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {
    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['prefix' => 'admin','controller' => 'Users', 'action' => 'login']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    //$routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks(DashedRoute::class);
});
Router::prefix('admin', function ($routes) {
    $routes->connect('/', ['controller' => 'Users', 'action' => 'login']);
    $routes->extensions(['json', 'xml']);
    // All routes here will be prefixed with `/admin`
    // And have the prefix => admin route element added.
    $routes->fallbacks(DashedRoute::class);
});
/**
 * Load all plugin routes. See the Plugin documentation on
 * how to customize the loading of plugin routes.
 */
Plugin::routes();

src/Model/Entity/User.php
<?php
namespace App\Model\Entity;

use Cake\ORM\Entity;

use Cake\ORM\TableRegistry;

use Cake\Auth\DefaultPasswordHasher;

/**
 * User Entity
 *
 * @property int $id
 * @property int $group_id
 * @property int $role_id
 * @property string $username
 * @property string $password
 * @property string $email
 * @property \Cake\I18n\FrozenTime $created
 * @property \Cake\I18n\FrozenTime $modified
 */
class User extends Entity
{
	public $hasOne = array('Role');
    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        'group_id' => true,
        'role_id' => true,
        'username' => true,
        'password' => true,
        'email' => true,
        'created' => true,
        'modified' => true
    ];

    /**
     * Fields that are excluded from JSON versions of the entity.
     *
     * @var array
     */
    protected $_hidden = [
        'password'
    ];
	
	    public function parentNode() {
        if (!$this->id) {
            return null;
        }
        if (isset($this->role_id)) {
            $roleId = $this->role_id;
        } else {
            $Users = TableRegistry::get('Users');
            $user = $Users->find('all', ['fields' => ['role_id']])->where(['id' => $this->id])->first();
            $roleId = $user->role_id;
        }
        if (!$roleId) {
            return null;
        }
        return ['Roles' => ['id' => $roleId]];
    }
	

    protected function _setPassword($password)
    {
        if (strlen($password) > 0) {
            return (new DefaultPasswordHasher)->hash($password);
        }
    }
}

src/Model/Table/UsersTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Users Model
 *
 * @property |\Cake\ORM\Association\BelongsTo $Groups
 * @property |\Cake\ORM\Association\BelongsTo $Roles
 *
 * @method \App\Model\Entity\User get($primaryKey, $options = [])
 * @method \App\Model\Entity\User newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\User[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\User|bool save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\User patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\User[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\User findOrCreate($search, callable $callback = null, $options = [])
 *
 * @mixin \Cake\ORM\Behavior\TimestampBehavior
 */
class UsersTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);


        $this->addBehavior('Acl.Acl', ['type' => 'requester']);
		$this->setTable('users');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');

        $this->addBehavior('Timestamp');
		
		

        $this->belongsTo('Groups', [
            'foreignKey' => 'group_id',
            'joinType' => 'INNER'
        ]);
        $this->belongsTo('Roles', [
            'foreignKey' => 'role_id',
            'joinType' => 'INNER'
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmpty('id', 'create');

        $validator
            ->scalar('username')
            ->maxLength('username', 50)
            ->requirePresence('username', 'create')
            ->notEmpty('username')
            ->add('username', 'unique', ['rule' => 'validateUnique', 'provider' => 'table']);

        $validator
            ->scalar('password')
            ->maxLength('password', 255)
            ->requirePresence('password', 'create')
            ->notEmpty('password');

        $validator
            ->email('email')
            ->requirePresence('email', 'create')
            ->notEmpty('email')
            ->add('email', 'unique', ['rule' => 'validateUnique', 'provider' => 'table']);

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->isUnique(['username']));
        $rules->add($rules->isUnique(['email']));
        $rules->add($rules->existsIn(['group_id'], 'Groups'));
        $rules->add($rules->existsIn(['role_id'], 'Roles'));

        return $rules;
    }
}

src/Controller/Admin/UsersController.php
<?php
namespace App\Controller\Admin;

use App\Controller\AppController;
use Cake\Event\Event;
use Cake\Auth\DefaultPasswordHasher;

/**
 * Users Controller
 *
 * @property \App\Model\Table\UsersTable $Users
 *
 * @method \App\Model\Entity\User[] paginate($object = null, array $settings = [])
 */
class UsersController extends AppController
{   
    public $paginate = [
        // Other keys here.
        'limit' => 20
    ];
    public $helpers = [
        'Paginator' => ['templates' => 'paginator-templates']
    ];
    //allowed action without login
    public function beforeFilter(Event $event)
    {
        parent::beforeFilter($event);
		$this->viewBuilder()->setTheme('Rokcrm');
        // Allow users to register and logout.
        // You should not add the "login" action to allow list. Doing so would
        // cause problems with normal functioning of AuthComponent.
        $this->Auth->allow(['logout']);
    }

    //login
    public function login()
    {
		$this->viewBuilder()->setTheme('Rok');
		//$this->layout = 'login';
        $this->viewBuilder()->setLayout('login');
        if ($this->Auth->user()) {
            return $this->redirect(['action' => 'index']);
        }
        //echo (new DefaultPasswordHasher)->hash('admin123');
        if ($this->request->is('post')) {
            $user = $this->Auth->identify();
			
            if ($user) {
                $this->Auth->setUser($user);
                return $this->redirect($this->Auth->redirectUrl());
            }
            $this->Flash->error(__('Invalid username or password, try again'));
        }
    }

    //logout
    public function logout()
    {
        return $this->redirect($this->Auth->logout());
    }

    /**
     * Index method
     *
     * @return \Cake\Http\Response|void
     */

    public function index()
    {
        
    }

    //user lsiting
    public function listing()
    {
        $this->paginate = [
        'contain' => ['Roles','Groups']
        ];
		$users = $this->paginate($this->Users);
	
        $this->set(compact('users'));
        $this->set('_serialize', ['users']);
    }
    /**
     * View method
     *
     * @param string|null $id User id.
     * @return \Cake\Http\Response|void
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null)
    {
        $user = $this->Users->get($id, [
            'contain' => []
        ]);
		
        $this->set('user', $user);
        $this->set('_serialize', ['user']);
        return $this->redirect(['action' => 'edit',$id]);
    }

    /**
     * Add method
     *
     * @return \Cake\Http\Response|null Redirects on successful add, renders view otherwise.
     */
    public function add()
    {
		
		//$this->layout = 'login';
       // $this->viewBuilder()->setLayout('login');
        $user = $this->Users->newEntity();
        if ($this->request->is('post')) {
            $user = $this->Users->patchEntity($user, $this->request->getData());
            if ($this->Users->save($user)) {
                $this->Flash->success(__('The user has been saved.'));

                return $this->redirect(['action' => 'listing']);
            }
            $this->Flash->error(__('The user could not be saved. Please, try again.'));
        }
		$this->loadModel('Roles');
		$this->loadModel('Groups');
        $this->set(compact('user'));
		$roles = $this->Roles->find('list');
		$this->set('roles', $roles);
		$groups = $this->Groups->find('list');
		$this->set('groups', $groups);
		//print_r($roles);
        $this->set('_serialize', ['user']);
    }

    /**
     * Edit method
     *
     * @param string|null $id User id.
     * @return \Cake\Http\Response|null Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit($id = null)
    {
        $user = $this->Users->get($id, [
            'contain' => []
        ]);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $user = $this->Users->patchEntity($user, $this->request->getData());
            if ($this->Users->save($user)) {
                $this->Flash->success(__('The user has been saved.'));

                return $this->redirect(['action' => 'listing']);
            }
            $this->Flash->error(__('The user could not be saved. Please, try again.'));
        }
		
		$this->loadModel('Roles');
		$this->loadModel('Groups');
        $this->set(compact('user'));
		$roles = $this->Roles->find('list',array('conditions'=>array('group_id'=>$user->group_id)));
		$this->set('roles', $roles);
		$groups = $this->Groups->find('list');
		$this->set('groups', $groups);
		
        $this->set(compact('user'));
        $this->set('_serialize', ['user']);
    }

    /**
     * Delete method
     *
     * @param string|null $id User id.
     * @return \Cake\Http\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $user = $this->Users->get($id);
        if ($this->Users->delete($user)) {
            $this->Flash->success(__('The user has been deleted.'));
        } else {
            $this->Flash->error(__('The user could not be deleted. Please, try again.'));
        }

        return $this->redirect(['action' => 'index']);
    }
	
	
	/**
     * Get Role method
     *
     * @param string|null $group_id Group id.
     * @return \Cake\Http\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
	private function getRole($group_id = null)
    {
		$this->loadModel('Roles');
		$roles = $this->Roles->find('list',array('conditions'=>array('group_id'=>$group_id)));
		$roles_str = '';
		if(!empty($roles))
		{
			foreach($roles as $k=>$v)
			{
				$roles_str = "<option value=".$k.">".$v."</option>";
			}
		}
        return $roles_str;
    }
	
	/**
     * Ajax Role By Group method
     *
     * @param string|null .
     * @return \Cake\Http\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
	public function ajaxRoleByGroup()
    {
        if ($this->request->is(['ajax', 'post'])) 
        {
            $id = $this->request->query('id');
            $data = ['data' => ['roles' => $this->getRole($id)]];
			$resultJ = json_encode($data);
			$this->response->type('json');
            $this->response->body($resultJ);
            return $this->response;
            //return json_encode($data);
        }
    }
}

src/Template/Admin/Users/add.ctp
<?php
/**
  * @var \App\View\AppView $this
  */
?>
<div class="container">
<?= $this->Flash->render() ?>
<?= $this->Form->create($user,['id'=>'user_add']) ?>
  <div class="">
    <div class="card-body">
        <div class="form-group row">
        <label for="example-text-input" class="col-2 col-form-label">User Name</label>
            <div class="col-md-6 col-xs-12">
                <?= $this->Form->control('username',['label' =>false,'class' => 'form-control required','placeholder' => 'Enter username']) ?>
            </div>
        </div>
        <div class="form-group row">
            <label for="example-text-input" class="col-2 col-form-label">Password</label>
            <div class="col-10">
                <?= $this->Form->control('password',['label' =>false,'type' => 'password','class' => 'form-control required','placeholder' => 'Password']) ?>   
            </div>
        </div>
        <div class="form-group row">
            <label for="example-text-input" class="col-2 col-form-label">Email</label>
            <div class="col-10">
                <?= $this->Form->control('email',['label' =>false,'type' => 'email','class' => 'form-control required','placeholder' => 'Email']) ?>
            </div>
        </div>
		<div class="form-group row">
            <label for="example-text-input" class="col-2 col-form-label">Group</label>
            <div class="col-10">
                <?php 
				 $request = $this->Url->build(['action' => 'ajaxRoleByGroup', 'ext' => 'json']);
				echo $this->Form->control('group_id',['id' => 'groupField', 'rel' => $request,'class'=>'form-control required','options' => $groups,'label'=>false,'empty'=>'Select Group']);?>
            </div>
        </div>
        <div class="form-group row">
            <label for="example-text-input" class="col-2 col-form-label">Role</label>
            <div class="col-10">
                <?php echo $this->Form->control('role_id',['id' => 'roleField','class'=>'form-control required','options' => array(),'label'=>false]);?>
            </div>
        </div>
      
        <div class="form-group row">
            <label for="example-text-input" class="col-2 col-form-label"></label>
            <div class="col-10">
                <?= $this->Form->button('Submit',['class' => 'btn btn-primary btn-block col-sm-4']); ?>
            </div>
        </div>
      </form>
    </div>
  </div>
  <?= $this->Form->end() ?>
</div>
<script>
$(document).ready(function() {
    $('#groupField').change(function() 
    {
        var targeturl = $(this).attr('rel');
        var group_id = $(this).val();
        $.ajax({
            type: 'get',
            url: targeturl + '&id=' + group_id,
            beforeSend: function(xhr) 
            {
                xhr.setRequestHeader('Content-type', 'application/x-www-form-urlencoded');
            },
            success: function(response) 
            {
                if (response.data) 
                {
                    $('#roleField').html(response.data.roles);
                }
            },
            error: function(e) 
            {
                alert("An error occurred: " + e.responseText.message);
                console.log(e);
            }
        });
    });
});
</script>

src/Template/Admin/Users/edit.ctp
<?php
/**
  * @var \App\View\AppView $this
  */
?>
<div class="container">
<?= $this->Flash->render() ?>
<?= $this->Form->create() ?>
  <div class="">
    <div class="card-body">
      <?= $this->Form->create($user) ?>
        <div class="form-group row">
        <label for="example-text-input" class="col-2 col-form-label">User Name</label>
            <div class="col-10">
                <?= $this->Form->control('username',['label' =>false,'class' => 'form-control','placeholder' => 'Enter username']) ?>
            </div>
        </div>
        <div class="form-group row">
            <label for="example-text-input" class="col-2 col-form-label">Password</label>
            <div class="col-10">
                <?= $this->Form->control('password',['label' =>false,'type' => 'password','class' => 'form-control','placeholder' => 'Password']) ?>   
            </div>
        </div>
        <div class="form-group row">
            <label for="example-text-input" class="col-2 col-form-label">Email</label>
            <div class="col-10">
                <?= $this->Form->control('email',['label' =>false,'type' => 'email','class' => 'form-control ','placeholder' => 'Email']) ?>
            </div>
        </div>
		<div class="form-group row">
            <label for="example-text-input" class="col-2 col-form-label">Group</label>
            <div class="col-10">
                <?php 
				 $request = $this->Url->build(['action' => 'ajaxRoleByGroup', 'ext' => 'json']);
				echo $this->Form->control('group_id',['id' => 'groupField', 'rel' => $request,'class'=>'form-control required','options' => $groups,'label'=>false,'empty'=>'Select Group']);?>
            </div>
        </div>
		  <div class="form-group row">
			<label for="example-text-input" class="col-2 col-form-label">Role</label>
			<div class="col-10">
				<?php echo $this->Form->control('role_id',['id' => 'roleField','class'=>'form-control required','options' => $roles,'label'=>false]);?>
			</div>
		</div>
       
        
        <div class="form-group row">
            <label for="example-text-input" class="col-2 col-form-label"></label>
            <div class="col-10">
                <?= $this->Form->button('Submit',['class' => 'btn btn-primary btn-block col-sm-4']); ?>
            </div>
        </div>
      </form>
    </div>
  </div>
  <?= $this->Form->end() ?>
</div>
<script>
$(document).ready(function() {
    $('#groupField').change(function() 
    {
        var targeturl = $(this).attr('rel');
        var group_id = $(this).val();
        $.ajax({
            type: 'get',
            url: targeturl + '&id=' + group_id,
            beforeSend: function(xhr) 
            {
                xhr.setRequestHeader('Content-type', 'application/x-www-form-urlencoded');
            },
            success: function(response) 
            {
                if (response.data) 
                {
                    $('#roleField').html(response.data.roles);
                }
            },
            error: function(e) 
            {
                alert("An error occurred: " + e.responseText.message);
                console.log(e);
            }
        });
    });
});
</script>

src/Template/Admin/Users/index.ctp
<?php echo $this->element('cards');?>
<?php echo $this->element('chart');?>
<?php echo $this->element('bar_pie');?>

src/Template/Admin/Users/listing.ctp
<?php
/**
  * @var \App\View\AppView $this
  * @var \App\Model\Entity\User[]|\Cake\Collection\CollectionInterface $users
  */
?>

<div class="users index table-responsive">
    <h3><?= __('Users') ?></h3>
    <div class="tscroll">
        <table class="table table-bordered" width="100%" cellspacing="0">
            <thead>
                <tr>
                    <th scope="col"><?= $this->Paginator->sort('id') ?></th>
                    <th scope="col"><?= $this->Paginator->sort('username') ?></th>
                    <th scope="col"><?= $this->Paginator->sort('email') ?></th>
					 <th scope="col"><?= $this->Paginator->sort('group_id') ?></th>
                    <th scope="col"><?= $this->Paginator->sort('role_id') ?></th>
                    <th scope="col"><?= $this->Paginator->sort('created') ?></th>
                    <th scope="col"><?= $this->Paginator->sort('modified') ?></th>
                    <th scope="col" class="actions"><?= __('Actions') ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($users as $user): ?>
                <tr>
                    <td><?= $this->Number->format($user->id) ?></td>
                    <td><?= h($user->username) ?></td>
                    <td><?= h($user->email) ?></td>
					<td><?= h($user->group->name) ?></td>
                    <td><?= h($user->role->name) ?></td>
                    <td><?= h($user->created) ?></td>
                    <td><?= h($user->modified) ?></td>
                    <td class="actions">
                        <?= $this->Html->link(__('View/Edit'), ['action' => 'edit', $user->id]) ?>
                        <?= $this->Form->postLink(__('Delete'), ['action' => 'delete', $user->id], ['confirm' => __('Are you sure you want to delete # {0}?', $user->id)]) ?>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <div class="paginator">
        <ul class="pagination">
            <?= $this->Paginator->prev('< ' . __('previous')) ?>
            <?= $this->Paginator->numbers() ?>
            <?= $this->Paginator->next(__('next') . ' >') ?>
        </ul>
        <p><?= $this->Paginator->counter(['format' => __('Page {{page}} of {{pages}}, showing {{current}} record(s) out of {{count}} total')]) ?></p>
    </div>
</div>

src/Template/Admin/Users/login.ctp
<?php /*<div class="container">
<?= $this->Flash->render() ?>
<?= $this->Form->create(null,['class'=>'user_login','id'=>'user_login']) ?>
	<div class="mx-auto mt-5 text-center">
		<img src="<?php echo $this->Url->image('roklogo.png');?>"/>
	</div>
  <div class="card card-login mx-auto mt-5">
    <div class="card-header">
      Login
    </div>
    <div class="card-body">
      <form>
        <div class="form-group">
          <?= $this->Form->control('username',['class' => 'form-control required','placeholder' => 'Enter username']) ?>
        </div>
        <div class="form-group">
          <?= $this->Form->control('password',['type' => 'password','class' => 'form-control required','placeholder' => 'Password']) ?>
        </div>
        <?= $this->Form->button('Login',['class' => 'btn btn-primary btn-block loginbutton']); ?>
      </form>
    </div>
  </div>
  <?= $this->Form->end() ?>
</div>*/ ?>

<div class="row">
					<div class="col-sm-10 col-sm-offset-1">
						<div class="login-container">
							<div class="center">
								<h1>
								 <img src="<?php echo $this->Url->image('logo.png');?>" width="200">
									<?php /*<i class="ace-icon fa fa-leaf green"></i>
									<span class="red">ROK</span>
									<span class="white" id="id-text2">HARDWARE</span>*/ ?>
								</h1>
								<?php /*<h4 class="blue" id="id-company-text">&copy; CRM</h4>*/ ?>
							</div>

							<div class="space-6"></div>

							<div class="position-relative">
								<div id="login-box" class="login-box visible widget-box no-border">
									<div class="widget-body">
										<div class="widget-main">
											<h4 class="header blue lighter bigger">
												<i class="ace-icon fa fa-coffee green"></i>
												Please Enter Your Information
											</h4>

											<div class="space-6"></div>
<?= $this->Flash->render() ?>
											<?= $this->Form->create() ?>
												<fieldset>
													<label class="block clearfix">
														<span class="block input-icon input-icon-right">
															<?= $this->Form->input('username',array('class'=>'form-control','placeholder'=>'Username','label'=>false)) ?>
															<i class="ace-icon fa fa-user"></i>
														</span>
													</label>

													<label class="block clearfix">
														<span class="block input-icon input-icon-right">
															<?= $this->Form->input('password',array('class'=>'form-control','placeholder'=>'Password','label'=>false)) ?>
															<i class="ace-icon fa fa-lock"></i>
														</span>
													</label>

													<div class="space"></div>

													<div class="clearfix">
														<?php /*<label class="inline">
															<input type="checkbox" class="ace" />
															<span class="lbl"> Remember Me</span>
														</label>*/ ?>
														<button type="submit" class="width-35 pull-right btn btn-sm btn-primary">
															<i class="ace-icon fa fa-key"></i>
															<span class="bigger-110">Login</span>
														</button>
													</div>

													<div class="space-4"></div>
												</fieldset>
											<?= $this->Form->end() ?>

										</div><!-- /.widget-main -->

										<div class="toolbar clearfix">
											<div>
												<a href="#" data-target="#forgot-box" class="forgot-password-link">
													<i class="ace-icon fa fa-arrow-left"></i>
													I forgot my password
												</a>
											</div>

											<?php /*<div>
												<a href="#" data-target="#signup-box" class="user-signup-link">
													I want to register
													<i class="ace-icon fa fa-arrow-right"></i>
												</a>
											</div>*/ ?>
										</div>
									</div><!-- /.widget-body -->
								</div><!-- /.login-box -->

								<div id="forgot-box" class="forgot-box widget-box no-border">
									<div class="widget-body">
										<div class="widget-main">
											<h4 class="header red lighter bigger">
												<i class="ace-icon fa fa-key"></i>
												Retrieve Password
											</h4>

											<div class="space-6"></div>
											<p>
												Enter your email and to receive instructions
											</p>

											<form>
												<fieldset>
													<label class="block clearfix">
														<span class="block input-icon input-icon-right">
															<input type="email" class="form-control" placeholder="Email" />
															<i class="ace-icon fa fa-envelope"></i>
														</span>
													</label>

													<div class="clearfix">
														<button type="button" class="width-35 pull-right btn btn-sm btn-danger">
															<i class="ace-icon fa fa-lightbulb-o"></i>
															<span class="bigger-110">Send Me!</span>
														</button>
													</div>
												</fieldset>
											</form>
										</div><!-- /.widget-main -->

										<div class="toolbar center">
											<a href="#" data-target="#login-box" class="back-to-login-link">
												Back to login
												<i class="ace-icon fa fa-arrow-right"></i>
											</a>
										</div>
									</div><!-- /.widget-body -->
								</div><!-- /.forgot-box -->

							</div><!-- /.position-relative -->
<?php /*
							<div class="navbar-fixed-top align-right">
								<br />
								&nbsp;
								<a id="btn-login-dark" href="#">Dark</a>
								&nbsp;
								<span class="blue">/</span>
								&nbsp;
								<a id="btn-login-blur" href="#">Blur</a>
								&nbsp;
								<span class="blue">/</span>
								&nbsp;
								<a id="btn-login-light" href="#">Light</a>
								&nbsp; &nbsp; &nbsp;
							</div>
							*/ ?>
						</div>
					</div><!-- /.col -->
				</div><!-- /.row -->

src/Template/Admin/Users/view.ctp
<?php
/**
  * @var \App\View\AppView $this
  * @var \App\Model\Entity\User $user
  */
?>
<div class="users view large-9 medium-8 columns content">
    <table class="vertical-table">
        <tr>
            <th scope="row"><?= __('Username') ?></th>
            <td><?= h($user->username) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Password') ?></th>
            <td><?= h($user->password) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Email') ?></th>
            <td><?= h($user->email) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Id') ?></th>
            <td><?= $this->Number->format($user->id) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Created') ?></th>
            <td><?= h($user->created) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Modified') ?></th>
            <td><?= h($user->modified) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Status') ?></th>
            <td><?= $user->status ? __('Yes') : __('No'); ?></td>
        </tr>
    </table>
</div>